== User Defined sc Neo4j Functions - Procedures


=== Setup

- edit neo4j.conf and add  sc.*  e.g.: 

[source,neo4j.conf]
----
vi /etc/neo4j/neo4j.conf
...
dbms.security.procedures.unrestricted=apoc.*,sc.*
dbms.security.procedures.whitelist=apoc.*,sc.*
----
- copy sc-neo4j-3.4.x.x.jar to Neo4j plugins directory e.g.:

[source,bash]
----
cp ./sc-neo4j-3.4.0.0.jar /var/lib/neo4j/plugins
----
- restart neo4j services
[source,bash]
----
service neo4j restart
----

- check for sc.xxxxxxx with: 
[source,cypher]
----
CALL dbms.functions()
CALL dbms.procedures()
----

- loggging: 
[source,bash]
----
# check dbms.logs.debug.level in the neo4j.conf - set to DEBUG
tail -f /var/log/neo4j/debug.log
----

=== http post
==== urlEncodeString - function
- sc.rest.urlEncodeString('string') - return url encoded string

====== Example
[source,cypher]
----
RETURN sc.rest.urlEncodeString('aaa.bbb@email.com {jsonString:"!"#$&/()"}') AS urlEncodeString
----
[source,cypher]
----
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"urlEncodeString"                                                     +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"aaa.bbb%40email.com+%7BjsonString%3A%22%21%22%23%24%26%2F%28%29%22%7D+
+"                                                                     +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----


==== httpPostJson - function
Run http/https json post and receive response from REST - based on Apache HttpComponents!

- sc.rest.httpJsonPost(\"url string\", {json document}) - return json document
- sc.rest.httpPostNode(\"url string\", neo4jNode) - return json document
- sc.rest.httpPostRelationship(\"url string\", neo4jRelationship) - return json document

====== Example
node.js REST server
[source,node.js]
----
var express = require('express')
var http = require('http');
var https = require('https');
var bodyParser = require('body-parser');
var fs = require('fs');

var app = express();
app.use(bodyParser.json());
http.createServer(app).listen(80);
console.log("http server started port 8080 - https 8443")

var pk = fs.readFileSync(__dirname+'\\server.key', 'utf8');
var pc = fs.readFileSync(__dirname+'\\server.crt', 'utf8');
var httpsOptions = {
    key: pk,
    cert: pc,
    secureProtocol: "TLSv1_2_method"
};

https.createServer(httpsOptions, app).listen({port: 8443}); 
http.createServer(app).listen(8080);

app.post('/restTest', function (req, res) {
    console.log('/restTest', req)
    var responseJson = {
        "error": null,
        "string": "string",
        "boolean": true,
        "integer": 123,
        "float": 123.456,
        "object": {
            "string": "string",
            "boolean": true,
            "integer": 123
        },
        array: ["string", true, 123, 123.456, {
                "string": "string",
                "boolean": true,
                "integer": 123
            }],
        "request": req.body,
    }
    res.json(responseJson);
});
----
httpPostJson
[source,cypher]
----
RETURN sc.rest.httpPostJson("http://127.0.0.1:8080/restTest", {name:123}) AS postResponse
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"postResponse"                                                        +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+{"request":{"name":123.0},"boolean":true,"string":"string","array":["s+
+tring",true,123.0,123.456,{"string":"string","boolean":true,"integer":+
+123.0}],"integer":123.0,"error":null,"float":123.456,"object":{"string+
+":"string","boolean":true,"integer":123.0}}                           +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----

https options
[source,cypher]
----
RETURN sc.rest.httpPostJson("https://127.0.0.1:8443/restTest", {name:123}) AS postResponse
++++++++++++++++
+"postResponse"+
++++++++++++++++
+null          +
++++++++++++++++
----


[source,cypher]
----
RETURN sc.rest.httpPostJson("https://127.0.0.1:8443/restTest", {name:123},{enableInsecureHttps: true}) AS postResponse
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"postResponse"                                                        +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+{"request":{"name":123.0},"boolean":true,"string":"string","array":["s+
+tring",true,123.0,123.456,{"string":"string","boolean":true,"integer":+
+123.0}],"integer":123.0,"error":null,"float":123.456,"object":{"string+
+":"string","boolean":true,"integer":123.0}}                           +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----

error handling
[source,cypher]
RETURN sc.rest.httpPostJson("https://127.0.0.1:8443/restTest", {name:123},{enableInsecureHttps: false, enableErrorMessage:false}) AS postResponse
++++++++++++++++
+"postResponse"+
++++++++++++++++
+null          +
++++++++++++++++
----


[source,cypher]
----
RETURN sc.rest.httpPostJson("https://127.0.0.1:8443/restTest", {name:123},{enableInsecureHttps: false, enableErrorMessage:true}) AS postResponse
+++++++++++++++++++++++++
+"postResponse"         +
+++++++++++++++++++++++++
+{"error":"IOException"}+
+++++++++++++++++++++++++
----

==== httpPostNode - function
[source,cypher]
----
MATCH (n:scTestNode) DETACH DELETE n;
CREATE (n:scTestNode {string:"string", integer:123, boolean:true, float:123.456}) RETURN n;

MATCH (n:scTestNode)
RETURN sc.rest.httpPostNode(
   "http://127.0.0.1/restTest", 
   n,
   {enableInsecureHttps: false, enableErrorMessage:false}
) 
AS postResponseNode
----
[source,cypher]
----
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"postResponseNode"                                                    +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+{"request":{"boolean":true,"integer":123.0,"string":"string","float":1+
+23.456},"boolean":true,"string":"string","array":["string",true,123.0,+
+123.456,{"string":"string","boolean":true,"integer":123.0}],"integer":+
+123.0,"error":null,"float":123.456,"object":{"string":"string","boolea+
+n":true,"integer":123.0}}                                             +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----

==== httpPostRelationship - function
[source,cypher]
----
MATCH ()-[r:scTesttRelationship]->() DELETE r
CREATE (:scTestNode)-[r:scTesttRelationship {string:"string", integer:123, boolean:true, float:123.456}]->(:scTestNode) RETURN r

MATCH ()-[r:scTesttRelationship]->()  
RETURN sc.rest.httpPostRelationship("http://127.0.0.1/restTest", r) AS postResponseRelationship
----
[source,cypher]
----
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"postResponseRelationship"                                            +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+{"request":{"boolean":true,"integer":123.0,"string":"string","float":1+
+23.456},"boolean":true,"string":"string","array":["string",true,123.0,+
+123.456,{"string":"string","boolean":true,"integer":123.0}],"integer":+
+123.0,"error":null,"float":123.456,"object":{"string":"string","boolea+
+n":true,"integer":123.0}}                                             +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----





=== Cypher

==== Cypher Neo4j Java VM - functions/procedures
Store cypher query into Neo4j Java VM and run query when needed

- sc.cypher.addVm('name', 'cypher query', {cypher query parameters}) - add CYPHER Java VM calls
- sc.cypher.listVm() - list all CYPHER java VM calls
- sc.cypher.runProcedureVm(\"stringFunctionName\", {object:\"params\"} - run CYPHER from Java VM
- sc.cypher.deleteVm('name') - add CYPHER Java VM calls


====== Example
Add  queries:
[source,cypher]
----
RETURN sc.cypher.addVm('addTestNode', 'CREATE (n:scTestNode) SET n.name=$name RETURN n')
RETURN sc.cypher.addVm('listAllTestNodes', 'MATCH (n:scTestNode) RETURN n')
RETURN sc.cypher.addVm('deleteAllTestNodes', 'MATCH (n:scTestNode) DETACH DELETE n')

RETURN sc.cypher.listVm()
----
Use  queries:
[source,cypher]
----
CALL sc.cypher.runVm('addTestNode', {name:"nd01"})
CALL sc.cypher.runVm('addTestNode', {name:"nd02"})
CALL sc.cypher.runVm('addTestNode', {name:"nd03"})

CALL sc.cypher.runVm('listAllTestNodes', {name:"nd03"})

CALL sc.cypher.runVm('deleteAllTestNodes', {})
CALL sc.cypher.runVm('listAllTestNodes', {name:"nd03"})
----
Remove  queries:
[source,cypher]
----
RETURN sc.cypher.listVm()
RETURN sc.cypher.deleteVm('deleteAllTestNodes')
RETURN sc.cypher.listVm()
RETURN sc.cypher.deleteVm('addTestNode')
RETURN sc.cypher.deleteVm('listAllTestNodes')
RETURN sc.cypher.listVm()
----



==== Cypher Neo4j DB - functions/procedures
Store cypher query into Neo4j DB as nodes and run query when needed

- sc.cypher.addDb('name', 'cypher query', {cypher query parameters}) - add CYPHER Java VM calls
- sc.cypher.listDb() - list all CYPHER java VM calls
- sc.cypher.runProcedureDb(\"stringFunctionName\", {object:\"params\"} - run CYPHER from Java VM
- sc.cypher.deleteDb('name') - add CYPHER Java VM calls


====== Example
Add  queries:
[source,cypher]
----
CALL sc.cypher.addDb('addTestNode', 'CREATE (n:scTestNode) SET n.name=$name RETURN n')
CALL sc.cypher.addDb('listAllTestNodes', 'MATCH (n:scTestNode) RETURN n')
CALL sc.cypher.addDb('deleteAllTestNodes', 'MATCH (n:scTestNode) DETACH DELETE n')

RETURN sc.cypher.listDb()
----
Use  queries:
[source,cypher]
----
CALL sc.cypher.runDb('listAllTestNodes', {name:"nd03"})

CALL sc.cypher.runDb('addTestNode', {name:"nd01"})
CALL sc.cypher.runDb('addTestNode', {name:"nd02"})
CALL sc.cypher.runDb('addTestNode', {name:"nd03"})

CALL sc.cypher.runDb('listAllTestNodes', {name:"nd03"})

CALL sc.cypher.runDb('deleteAllTestNodes', {})
CALL sc.cypher.runDb('listAllTestNodes', {name:"nd03"})
----
Remove  queries:
[source,cypher]
----
RETURN sc.cypher.listDb()
CALL sc.cypher.deleteDb('deleteAllTestNodes')
RETURN sc.cypher.listDb()
CALL sc.cypher.deleteDb('addTestNode')
CALL sc.cypher.deleteDb('listAllTestNodes')
RETURN sc.cypher.listDb()
----



cypher node management
[source,cypher]
----
// find CypherRunDb
MATCH (n:CypherRunDb) 
RETURN n
----
[source,cypher]
----
// delete all CypherRunDb
MATCH (n:CypherRunDb) 
DETACH DELETE n
----
==== Cypher Neo4j VM - DB Examples
====== example - string return

[source,cypher]
----
// create 
CREATE (n:CypherRunDb) 
SET 
    n.name="stringFunction",
    n.type="CypherRunDb",  
    n.query= "RETURN \"string from query\" AS string" 
RETURN n
----
[source,cypher]
----
// check 
MATCH (n:CypherRunDb) 
WHERE n.name="stringFunction"
RETURN n
----
[source,cypher]
----
// run
CALL sc.cypher.runDb("stringFunction", {}) 
----


====== example - url creating 

[source,cypher]
----
// create 
RETURN sc.cypher.addVm("getUrl", "RETURN \"http://:\" + $ipAddress + \"/\"+ $restMethod AS url")

----
[source,cypher]
----
// run
CALL sc.cypher.runVm("getUrl", {ipAddress:"127.0.0.1",restMethod:"testPost"})
----


====== example - search nodes with parameters

[source,cypher]
----
CREATE (n:person) SET n.name="abc";
CREATE (n:person) SET n.name="def";
CREATE (n:person) SET n.name="ghi";

RETURN sc.cypher.addVm("findPerson", "MATCH (n:person) WHERE n.name=$name RETURN n")
----

[source,cypher]
----
// run
CALL sc.cypher.runVm("findPerson", {name:"abc"})
----


==== Cypher Neo4j CRON - functions/procedures
Run cypher query by cron - based on cron4j library.

- sc.cron.list()  // list all cron jobs
- sc.cron.delete('cronName')  // remove cron job
- sc.cron.add('cronName','* * * * *','MATCH (n) RETURN n', {cypherQueryParams:'optional'},{cronScheduler':optional', cronDelay:0})   // add cron job
- sc.cron.run('cronName') // run cron job



====== Example
Add  CRON task:
[source,cypher]
----
WITH "MERGE (n:CronNode  ) ON CREATE SET n.created = timestamp(), n.count = 1 ON MATCH SET n.update = timestamp(), n.count = n.count+1 RETURN n" AS createTestNode 
CALL sc.cron.add('cronName','* * * * *',createTestNode) YIELD value AS cronAdd
RETURN cronAd

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"cronAdd"                                                             +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+{"name":"cronName","cronRunError":0,"cypherQuery":"MERGE (n:CronNode  +
+) ON CREATE SET n.created = timestamp(), n.count = 1 ON MATCH SET n.up+
+date = timestamp(), n.count = n.count+1 RETURN n","cronRunOk":0,"cronS+
+tring":"* * * * *","cypherParams":{}}                                 +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++



----

Check Neo4j CRON tasks.
[source,cypher]
----
RETURN sc.cron.list()
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"sc.cron.list()"                                                      +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+[{"name":"cronName","cronRunError":0,"cypherQuery":"MERGE (n:CronNode +
+ ) ON CREATE SET n.created = timestamp(), n.count = 1 ON MATCH SET n.u+
+pdate = timestamp(), n.count = n.count+1 RETURN n","cronRunOk":2,"cron+
+String":"* * * * *","cypherParams":{}}]                               +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----

Check Nodes created by Neo4j CRON.
[source,cypher]
----
MATCH (n:CronNode) RETURN n
----

Run Neo4j CRON task.
[source,cypher]
----
CALL sc.cron.run('cronName')
----




==== Cypher Neo4j MqTT client - functions/procedures
MqTT publish subscribe from Neo4j - based on org.eclipse.paho.client.mqttv3 library.

- RETURN sc.mqtt.list() // list MqTT brokers
- RETURN sc.mqtt.add('mqttBrokerName', {brokerUrl:'tcp://iot.eclipse.org:1883', clientId:'123'  })   // add MqTT broker client
- RETURN sc.mqtt.delete('mqttBrokerName') // delete MqTT broker client
- CALL sc.mqtt.publish('mqttBrokerName', '/mqtt/topic/path', 'message') // publish message
- CALL sc.mqtt.subscribe('mqttBrokerName', '/mqtt/topic/path','cypherQuery' ) // subscribe cypher query to mqtt messages
- RETURN sc.mqtt.unSubscribe('mqttBrokerName', '/mqtt/topic/path') // subscribe cypher query to mqtt messages


====== Example
Add MqTT broker connection, subscribe to topic and publish:
[source,cypher]
----
RETURN sc.mqtt.add('mqttBrokerName', {brokerUrl:'tcp://iot.eclipse.org:1883' ,clientId:'Neo4jTestClient'  })
CALL sc.mqtt.subscribe('mqttBrokerName', '/mqtt/topic/path','CREATE (n:MqttNode) SET n.name=$name')
CALL sc.mqtt.publish('mqttBrokerName', '/mqtt/topic/path',{name:"abc"})
RETURN sc.mqtt.list()
----

Check Nodes created by Neo4j MqTT subsciber.
[source,cypher]
----
MATCH (n:MqttNode) RETURN n
----

List MqTT broker connections.
[source,cypher]
----
RETURN sc.mqtt.list()
----

Remove MqTT subscription.
[source,cypher]
----
RETURN sc.mqtt.unSubscribe('mqttBrokerName','/mqtt/topic/path')
----

[source,cypher]
----
 RETURN sc.mqtt.delete('mqttBrokerName')
----







===  EVAL JavaScript Neo4j Java VM - function
Run JavaScript via java Nashorn JavaScript engine for the JVM and receive JavaScript response


- sc.javascript.run("javascript script string", jsParams)"  - javascript response          
- sc.javascript.addDb('name', 'cypher query', {cypher query parameters}) - add JavaScript Java VM calls
- sc.javascript.listDb() - list all JavaScript java VM calls
- sc.javascript.runProcedureDb(\"stringFunctionName\", {object:\"params\"} - run JavaScript from Java VM
- sc.javascript.deleteDb('name') - add JavaScript Java VM calls
!!! jsParams  - parameters JavaScript var name!

====== Example run JavaScript
[source,cypher]
----
WITH "
return 'Hello, from javascript with string parameter: ' + jsParams + '!';"
AS javaScriptString

RETURN sc.javascript.run(javaScriptString, "input params string")
----  
[source,cypher]
----
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"sc.javascript.run(javaScriptString, "input params string")"        +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"Hello, from javascript with string parameter: input params string!"+
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----


[source,cypher]
----
WITH "
var properties = JSON.parse(jsParams); 
var replyString = 'return Hello, from javascript with json object params: ' + properties.name + '!';
return replyString;"
AS javaScriptString

WITH "{\"name\":\"abc\", \"address\":\"def 12\"}" AS properties, javaScriptString

RETURN sc.javascript.run(javaScriptString, properties)
----   

[source,cypher]
----
WITH "
var properties = JSON.parse(jsParams); 
var replyObject = {
name:properties.name || 'default',
address:properties.address || 'default' ,
telephone:properties.telephone || 'default' 
};
return replyObject;"
AS checkInputDataJs

WITH "{\"name\":\"abc\", \"address\":\"def 12\"}" AS dataToCheck, checkInputDataJs
WITH  sc.javascript.run(checkInputDataJs, dataToCheck) AS jsResponse

RETURN jsResponse.telephone
----






====== Example register / use JavaScript

Add  javascript:
[source,cypher]
----
WITH "
var properties = JSON.parse(jsParams); 
var replyObject = {
name:properties.name || 'default',
address:properties.address || 'default' ,
telephone:properties.telephone || 'default' 
};
return replyObject;"
AS checkInputDataJs
RETURN sc.javascript.addVm('checkforTelephone', checkInputDataJs)


RETURN sc.javascript.listVm()
----
Use  javascript:
[source,cypher]
----
WITH "{\"name\":\"abc\", \"address\":\"def 12\"}" AS dataToCheck
RETURN sc.javascript.runVm('checkforTelephone', dataToCheck)


WITH "{\"name\":\"abc\", \"telephone\":\"12345 67 12\"}" AS dataToCheck
RETURN sc.javascript.runVm('checkforTelephone', dataToCheck)


RETURN sc.javascript.runVm('checkforTelephone', '{"name":"nd03"}')
----
Remove  javascript:
[source,cypher]
----
RETURN sc.javascript.listVm()
RETURN sc.javascript.deleteVm('checkforTelephone')
RETURN sc.javascript.listVm()
----





=== Export to JSON
==== jsonExportNode - function
- sc.jsonExportNode(neo4jNode) - return json Neo4j Node string"


====== Example
[source,cypher]
----
MATCH (n:scTestNode) DETACH DELETE n;
CREATE (n:scTestNode {string:"string", integer:123, boolean:true, float:123.456}) RETURN n;

MATCH (n:scTestNode)  RETURN sc.jsonExportNode(n) AS jsonExportNode;
----
[source,cypher]
----
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"jsonExportNode"                                                      +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"{_id:83,_labels:[scTestNode],_properties:{"boolean":true,"string":"st+
+ring","integer":123,"float":123.456}}"                                +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----

==== jsonExportRelationship - function
- sc.jsonExportRelationship(neo4jRelationship) - return json Neo4j Relationship string"

====== Example
[source,cypher]
----
MATCH ()-[r:scTesttRelationship]->() DELETE r
CREATE (:scTestNode)-[r:scTesttRelationship {string:"string", integer:123, boolean:true, float:123.456}]->(:scTestNode) RETURN r

MATCH ()-[r:scTesttRelationship]->()  RETURN sc.jsonExportRelationship(r) AS jsonExportRelationship
----
[source,cypher]
----
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"jsonExportRelationship"                                              +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+"{_id:33,_from:232,_to:233,_type:scTesttRelationship,_properties:{"boo+
+lean":true,"string":"string","integer":123,"float":123.456}}"         +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----


